stages:
  - build
  - run

image: docker:24.0.5
services:
  - docker:24.0.5-dind

build-job:
  stage: build
  script:
    - docker build -t my-python-app .

run-job:
  stage: run
  script:
    - docker run --rm my-python-app